import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import ProtectRoute from '@/components/functionComponents/protectRoute'

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <ProtectRoute />
            <body
                className={cn(
                    'bg-background min-h-screen font-sans antialiased',
                    fontSans.variable
                )}
            >
                <header className="fixed w-full">
                    <ul className="flex justify-end gap-x-4 px-8 py-4">
                        <li>
                            <Link href={'/'}>Home</Link>
                        </li>
                        <li>
                            <Link href={'/SkapaKonto'}>SkapaKonto</Link>
                        </li>
                        <li>
                            <Link href={'/LogaIn'}>LogaIn</Link>
                        </li>
                    </ul>
                </header>
                {children}
            </body>
        </html>
    )
}
